<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE METARS[ 
<!ELEMENT METARS (METAR*)>
<!ELEMENT METAR ( LOCATION?, LOCAL-DATE?, LOCAL-TIME? , WIND?, VISIBILITY?, SKY-CONDITIONS, TEMPERATURE , DEW-POINT?, RELATIVE-HUMIDITY?, ALTIMETER?, OB?) >
<!ATTLIST METAR ICAO-LOCATION CDATA #REQUIRED >
<!ATTLIST METAR UTC-DATE CDATA #REQUIRED >
<!ATTLIST METAR UTC-TIME CDATA #REQUIRED >
<!ATTLIST METAR CYCLE CDATA #REQUIRED >

<!ELEMENT LOCATION ( POLITICAL?, GEOGRAPHICAL? ) >

<!ELEMENT POLITICAL ( STATION?, CITY?, STATE?, COUNTRY? ) >
<!ELEMENT STATION (#PCDATA) >
<!ELEMENT CITY (#PCDATA) >
<!ELEMENT STATE (#PCDATA) >
<!ELEMENT COUNTRY (#PCDATA) >

<!ELEMENT GEOGRAPHICAL ( LONGITUDE?, LATITUDE?, ALTITUDE? ) >
<!ELEMENT LONGITUDE (#PCDATA) >
<!ELEMENT LATITUDE (#PCDATA) >
<!ELEMENT ALTITUDE (#PCDATA) >

<!ELEMENT LOCAL-DATE (#PCDATA) >
<!ELEMENT LOCAL-TIME (#PCDATA) >
<!ATTLIST LOCAL-TIME TIMEZONE CDATA #REQUIRED >

<!ELEMENT WIND (#PCDATA) >
<!ATTLIST WIND DIRECTION CDATA #IMPLIED >

<!ELEMENT VISIBILITY (#PCDATA) >
<!ELEMENT SKY-CONDITIONS (#PCDATA) >
<!ELEMENT TEMPERATURE (#PCDATA) >
<!ATTLIST TEMPERATURE UNITS (F|C) 'F'>

<!ELEMENT DEW-POINT (#PCDATA) >
<!ATTLIST DEW-POINT UNITS (F|C) 'F'>

<!ELEMENT RELATIVE-HUMIDITY (#PCDATA) >

<!ELEMENT ALTIMETER (#PCDATA) >
<!ATTLIST ALTIMETER UNITS (in.Hg|hPa) "in.Hg">

<!ELEMENT OB (#PCDATA) > 
]>

<METARS>
<METAR ICAO-LOCATION="KCAE" UTC-DATE="2017.09.29" UTC-TIME="0456" CYCLE="5" >
  <LOCATION>
    <POLITICAL>
      <STATION>Columbia Metropolitan Airport</STATION>
      <CITY>Columbia</CITY>
      <STATE>SC</STATE>
      <COUNTRY>United States</COUNTRY>
    </POLITICAL>
    <GEOGRAPHICAL>
      <LONGITUDE>33-56-31N</LONGITUDE>
      <LATITUDE>081-07-05W</LATITUDE>
      <ALTITUDE>73M</ALTITUDE>
    </GEOGRAPHICAL>
  </LOCATION>
  <LOCAL-DATE>Sep 28, 2017</LOCAL-DATE> 
  <LOCAL-TIME timezone="EST">11:56 PM</LOCAL-TIME>
  <WIND DIRECTION="010">5 MPH (5 KT):0</WIND>
  <VISIBILITY>10 mile(s):0</VISIBILITY>
  <SKY-CONDITIONS>clear</SKY-CONDITIONS>
  <TEMPERATURE UNITS="F">41.0</TEMPERATURE>
  <DEW-POINT UNITS="F">36.0</DEW-POINT>
  <RELATIVE-HUMIDITY>82%</RELATIVE-HUMIDITY>
  <ALTIMETER UNITS="in.Hg">29.98</ALTIMETER>
  <OB>KCAE 100456Z 01005KT 10SM CLR 05/02 A2998 RMK AO2 SLP152 T00500022 401170022</OB>
</METAR>
<METAR ICAO-LOCATION="KCAD" UTC-DATE="2017.09.29" UTC-TIME="0155" CYCLE="2" >
  <LOCATION>
    <POLITICAL>
      <CITY>Cadillac / Wexford County</CITY>
      <STATE>MI</STATE>
      <COUNTRY>United States</COUNTRY>
    </POLITICAL>
    <GEOGRAPHICAL>
      <LONGITUDE>44-17N</LONGITUDE>
      <LATITUDE>085-25W</LATITUDE>
    </GEOGRAPHICAL>
  </LOCATION>
  <LOCAL-DATE>Sep 28, 2017</LOCAL-DATE> 
  <LOCAL-TIME timezone="EST">9:55 PM</LOCAL-TIME>
  <WIND DIRECTION="220">7 MPH (6 KT):0</WIND>
  <VISIBILITY>10 mile(s):0</VISIBILITY>
  <SKY-CONDITIONS>overcast</SKY-CONDITIONS>
  <TEMPERATURE UNITS="F">58.1</TEMPERATURE>
  <DEW-POINT UNITS="F">44.8</DEW-POINT>
  <RELATIVE-HUMIDITY>61%</RELATIVE-HUMIDITY>
  <ALTIMETER UNITS="in.Hg">30.05</ALTIMETER>
  <OB>KCAD 290155Z AUTO 22006KT 10SM OVC100 14/07 A3005 RMK AO2 T01450071</OB>
</METAR>
</METARS>