<!DOCTYPE bill [
<!ELEMENT bill (identifier, summary, header, section+)>
<!ELEMENT identifier EMPTY>
<!ELEMENT header (chamber,date,sponsor,cosponsor*)>
<!ELEMENT chamber (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT sponsor (#PCDATA)>
<!ELEMENT cosponsor (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT section (#PCDATA|paragraph|subsection)*>
<!ELEMENT paragraph (#PCDATA|list)*>
<!ELEMENT subsection (#PCDATA|subsection|paragraph)*>
<!ELEMENT list (listItem+)>
<!ELEMENT listItem (#PCDATA)>

<!ATTLIST identifier congress CDATA #REQUIRED
                     chamber (House|Senate) #REQUIRED
                     session CDATA #REQUIRED
                     type (S|S.J.|S.Con.Res|S.Res.|H.R.|H.J.Res.|H.Con.Res.|H.Res.) #REQUIRED
                     number CDATA #REQUIRED>
<!ATTLIST section id CDATA #REQUIRED
                  title CDATA #IMPLIED>	
<!ATTLIST subsection id CDATA #REQUIRED
                     title CDATA #IMPLIED>
]>

<bill>
<identifier congress="114th Congress" chamber="Senate" session="1st Session" type="H.R." number="2802" />
<summary>To prevent discriminatory treatment of any person on the basis of views held with respect to marriage.</summary>
<header>
	<chamber>IN THE HOUSE OF REPRESENTATIVES</chamber>
	<date>June 17, 2015</date>
	<sponsor>Mr. Labrador</sponsor>
	<cosponsor>Mr. Collins of Georgia</cosponsor>
	<cosponsor>Mr. Jones</cosponsor>
	<cosponsor>Mr. Sessions</cosponsor>
</header>
<section id="1" title="SHORT TITLE">
	<paragraph>This Act may be cited as the “First Amendment Defense Act”.</paragraph>
</section>
<section id="2" title="FINDINGS">
	<paragraph>
	Congress finds the following:
		<list>
			<listItem>Leading legal scholars concur that conflicts between same-sex marriage and religious liberty are real and should be legislatively addressed.</listItem>
			<listItem>As the President stated in response to the decision of the Supreme Court on the Defense of Marriage Act in 2013, “Americans hold a wide range of views” on the issue of same-sex marriage, and “maintaining our Nation’s commitment to religious freedom” is “vital”.</listItem>
			<listItem>Nevertheless, in 2015, when asked whether a religious school could lose its tax-exempt status for opposing same-sex marriage, the Solicitor General of the United States represented to the United States Supreme Court that “[i]t’s certainly going to be an issue”.</listItem>
			<listItem>Protecting religious freedom from Government intrusion is a Government interest of the highest order. Legislatively enacted measures advance this interest by remedying, deterring, and preventing Government interference with religious exercise in a way that complements the protections mandated by the First Amendment to the Constitution of the United States.</listItem>
			<listItem>Laws that protect the free exercise of religious beliefs and moral convictions about marriage will encourage private citizens and institutions to demonstrate tolerance for those beliefs and convictions and therefore contribute to a more respectful, diverse, and peaceful society.</listItem>
		</list>
	</paragraph>
</section>
<section id="3" title="PROTECTION OF THE FREE EXERCISE OF RELIGIOUS BELIEFS AND MORAL CONVICTIONS.">
	<subsection id="a" title="IN GENERAL">
		<paragraph>
			Notwithstanding any other provision of law, the Federal Government shall not take any discriminatory action against a person, wholly or partially on the basis that such person believes or acts in accordance with a religious belief or moral conviction that marriage is or should be recognized as the union of one man and one woman, or that sexual relations are properly reserved to such a marriage.
		</paragraph>
	</subsection>
	<subsection id="b" title="DISCRIMINATORY ACTION DEFINED">
		<paragraph>
			As used in subsection (a), a discriminatory action means any action taken by the Federal Government to
			<list>
				<listItem>alter in any way the Federal tax treatment of, or cause any tax, penalty, or payment to be assessed against, or deny, delay, or revoke an exemption from taxation under section 501(a) of the Internal Revenue Code of 1986 of, any person referred to in subsection (a);</listItem>
				<listItem>disallow a deduction for Federal tax purposes of any charitable contribution made to or by such person;</listItem>
				<listItem>withhold, reduce, exclude, terminate, or otherwise deny any Federal grant, contract, subcontract, cooperative agreement, loan, license, certification, accreditation, employment, or other similar position or status from or to such person;</listItem>
				<listItem>withhold, reduce, exclude, terminate, or otherwise deny any benefit under a Federal benefit program from or to such person; or</listItem>
				<listItem>otherwise discriminate against such person.</listItem>
			</list>
		</paragraph>
	</subsection>
	<subsection id="c" title="ACCREDIDATION; LICENSURE; CERTIFICATION">
		<paragraph>
			The Federal Government shall consider accredited, licensed, or certified for purposes of Federal law any person that would be accredited, licensed, or certified, respectively, for such purposes but for a determination against such person wholly or partially on the basis that the person believes or acts in accordance with a religious belief or moral conviction that marriage is or should be recognized as the union of one man and one woman, or that sexual relations are properly reserved to such a marriage.
		</paragraph>
	</subsection>
</section>
<section id="4" title="JUDICIAL RELIEF">
	<subsection id="a" title="CAUSE OF ACTION">
		<paragraph>
			A person may assert an actual or threatened violation of this Act as a claim or defense in a judicial or administrative proceeding and obtain compensatory damages, injunctive relief, declaratory relief, or any other appropriate relief against the Federal Government. Standing to assert a claim or defense under this section shall be governed by the general rules of standing under Article III of the Constitution.
		</paragraph>
	</subsection>
	<subsection id="b" title="ADMINISTRATIVE REMEMDIES NOT REQUIRED">
		<paragraph>
			Notwithstanding any other provision of law, an action under this section may be commenced, and relief may be granted, in a United States district court without regard to whether the person commencing the action has sought or exhausted available administrative remedies.
		</paragraph>
	</subsection>
	<subsection id="c" title="ATTORNEYS' FEES">
		<paragraph>
			Section 722(b) of the Revised Statutes (42 U.S.C. 1988(b)) is amended by inserting “the First Amendment Defense Act,” after “the Religious Land Use and Institutionalized Persons Act of 2000,”.
		</paragraph>
	</subsection>
	<subsection id="d" title="AUTHORITY OF UNITED STATES TO ENFORCE THIS ACT">
		<paragraph>
			The Attorney General may bring an action for injunctive or declaratory relief against an independent establishment described in section 104(1) of title 5, United States Code, or an officer or employee of that independent establishment, to enforce compliance with this Act. Nothing in this subsection shall be construed to deny, impair, or otherwise affect any right or authority of the Attorney General, the United States, or any agency, officer, or employee of the United States, acting under any law other than this subsection, to institute or intervene in any proceeding.
		</paragraph>
	</subsection>
</section>
<section id="5" title="RULES OF CONSTRUCTION">
	<subsection id="a" title="BROAD CONSTRUCTION">
		<paragraph>
			This Act shall be construed in favor of a broad protection of free exercise of religious beliefs and moral convictions, to the maximum extent permitted by the terms of this Act and the Constitution.
		</paragraph>
	</subsection>
	<subsection id="b" title="NO PREEMPTION, REPEAL, Or NARROW CONSTRUCTION">
		<paragraph>
			Nothing in this Act shall be construed to preempt State law, or repeal Federal law, that is equally or more protective of free exercise of religious beliefs and moral convictions. Nothing in this Act shall be construed to narrow the meaning or application of any State or Federal law protecting free exercise of religious beliefs and moral convictions. Nothing in this Act shall be construed to prevent the Federal Government from providing, either directly or through a person not seeking protection under this Act, any benefit or service authorized under Federal law.
		</paragraph>
	</subsection>
	<subsection id="c" title="SEVERABILITY">
		<paragraph>
			If any provision of this Act or any application of such provision to any person or circumstance is held to be unconstitutional, the remainder of this Act and the application of the provision to any other person or circumstance shall not be affected.
		</paragraph>
	</subsection>
</section>
<section id="6" title="DEFINITIONS">
	<paragraph>
		<list>
			<listItem>FEDERAL BENEFIT PROGRAM.—The term “Federal benefit program” has the meaning given that term in section 552a of title 5, United States Code.</listItem>
			<listItem>FEDERAL GOVERNMENT.—The term “Federal Government” includes each authority of any branch of the Government of the United States.</listItem>
			<listItem>The term “person” means a person as defined in section 1 of title 1, United States Code, and includes any such person regardless of religious affiliation or lack thereof, and regardless of for-profit or nonprofit status.</listItem>
		</list>
	</paragraph>
</section>
</bill>